# Generated by Django 2.2.5 on 2020-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default_avatar.png', upload_to='avatars'),
        ),
    ]
