# Generated by Django 2.2.5 on 2020-08-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars'),
        ),
    ]
