# Generated by Django 2.2.5 on 2020-10-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='BotComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('color', models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black')], max_length=6, verbose_name='color')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussion.Bot', verbose_name='bot')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='bots',
            field=models.ManyToManyField(related_name='rooms', through='discussion.RoomUser', to='discussion.Bot'),
        ),
        migrations.AddField(
            model_name='roomuser',
            name='bot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='discussion.Bot'),
            preserve_default=False,
        ),
    ]
