# Generated by Django 2.2.5 on 2020-07-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20200721_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black')], max_length=6),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
