# Generated by Django 2.2.5 on 2020-10-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_auto_20201027_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bots',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', through='discussion.RoomUser', to='discussion.Bot'),
        ),
    ]
