# Generated by Django 2.2.5 on 2020-10-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20201028_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bots',
            field=models.ManyToManyField(related_name='rooms', through='discussion.RoomUser', to='discussion.Bot'),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.Bot'),
        ),
    ]
