# Generated by Django 2.2.5 on 2020-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_auto_20201028_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bots',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='discussion.Bot'),
        ),
    ]
