# Generated by Django 2.2.5 on 2020-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_auto_20201028_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bots',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='discussion.Bot'),
        ),
    ]
