# Generated by Django 2.2.5 on 2020-10-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0010_auto_20201028_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='avatar',
            field=models.ImageField(default='avatars/bot_avatar.jpg', upload_to='avatars'),
        ),
    ]
