# Generated by Django 2.2.5 on 2020-11-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0011_bot_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AlterModelOptions(
            name='botcomment',
            options={'verbose_name': 'Комментарии бота', 'verbose_name_plural': 'Комментарии ботов'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='bots',
        ),
        migrations.AddField(
            model_name='room',
            name='bots',
            field=models.ManyToManyField(blank=True, related_name='rooms', through='discussion.RoomBot', to='discussion.Bot'),
        ),
        migrations.AddField(
            model_name='roombot',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.Bot'),
        ),
        migrations.AddField(
            model_name='roombot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='roombot',
            unique_together={('room', 'bot')},
        ),
    ]
