# Generated by Django 2.2.15 on 2020-11-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0012_auto_20201102_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
        migrations.AddField(
            model_name='theme',
            name='decision',
            field=models.TextField(default='', verbose_name='decision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='problem',
            field=models.TextField(default='', verbose_name='problem'),
            preserve_default=False,
        ),
    ]
