# Generated by Django 2.2.15 on 2020-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0013_auto_20201117_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='closed'),
        ),
    ]
