# Generated by Django 2.2.15 on 2021-01-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0015_auto_20210106_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='started',
            field=models.BooleanField(default=False, verbose_name='started'),
        ),
    ]
